### ISSUE TITLE
Library missing from Bintray 

### ISSUE THREAD

**Issue by daniel-bunn** [hmrc/play-json-union-formatter#6]
It looks like this library isn't published to bintray.com anymore. I was unable to find it by searching here(https://bintray.com/bintray/jcenter) or browsing jcenter's tree hierarchy directly https://jcenter.bintray.com/uk/gov/hmrc/.

**Comment by crystalmark** [comment]
Hi Daniel,  It looks like it's still there, I can see the release candidate artefact here:

https://dl.bintray.com/hmrc/release-candidates/uk/gov/hmrc/play-json-union-formatter_2.11/1.3.0-4-gbe45468/

Tim

**Comment by daniel-bunn** [comment]
@crystalmark, Sorry about that. I was setting up Nexus to proxy bintray and I only setup `https://jcenter.bintray.com` to be proxied, so I was getting `UNRESOLVED DEPENDENCIES
uk.gov.hmrc#play-json-union-formatter_2.11;1.3.0: not found`. I add `https://dl.bintray.com/hmrc/releases` to be proxied and everything works as expected. Thanks for the help!
